function A_d_slip = A_d_slip(obj,in2,in3,dt,in5)
%A_d_slip
%    A_d_slip = A_d_slip(OBJ,IN2,IN3,DT,IN5)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024/01/21 08:34:07

u_lin1 = in3(1,:);
u_lin2 = in3(2,:);
x_lin3 = in2(3,:);
t2 = cos(u_lin2);
A_d_slip = reshape([1.0,0.0,0.0,0.0,1.0,0.0,-dt.*t2.*u_lin1.*sin(x_lin3),dt.*t2.*u_lin1.*cos(x_lin3),1.0],[3,3]);
end
